### ISSUE TITLE
gUM firing repeatedly for the same page load

### ISSUE THREAD

**Issue by jnoring** [w3c/mediacapture-main#304] opened 2016-01-11 17:51 UTC
I wanted to start a discussion around this defect: https://bugzilla.mozilla.org/show_bug.cgi?id=1212996

The bug basically boils down to this: in Firefox, every call to getUserMedia will show the gUM allow/deny prompt.

Example:

1. I visit https://www.xyz.com, which requests access to camera/microphone
2. gUM fires, showing the browser's allow/deny dialog
3. User allows
4. xyz.com has support for navigator.mediaDevices.enumerateDevices() and allows the user to change mic and camera in page
5. User changes their mic or camera
6. gUM fires, again showing the browser's allow/deny dialog

...step 6 is really the question: should a browser show that second allow/deny dialog?  Currently Chrome and Firefox are completely different in this regard:

1. Chrome: if the page is loaded via HTTPS, not only does that first allow grant the page access to *all* microphones and cameras, but it does so in perpetuity; the grant is interpreted as permanent for that page, _for all devices_.
2. Firefox: unless the user explicitly chooses the "allow always" option in the gUM dialog, Firefox prompts for every single gUM request, even if the user has already granted access.  The grant is interpreted as a grant _to a specific device_.

The spec isn't clear on what's correct here, leaving it to the browser implementation to decide:

> It is a User Agent choice whether it offers functionality to store permission to each device separately, all devices of a given class, or all devices; the choice needs to be apparent to the user, and permission must have been granted for the entire set whose permission is being stored, e.g., to store permission to use all cameras the user must have given permission to use all cameras and not just one.

...and it has a huge impact on a developer's ability to make their own device enumeration/selection.  My question is: should there be some updates to the spec to alleviate these issues?

**Comment by jnoring** [comment] 2016-01-11 17:51
As a developer, Chrome's permissions are easy to deal with; arguably they're overly permissive.  But Firefox's permissions are *extremely* hard to work with, for the following reasons:

1.  A user could reject the second request (most likely accidentally), which means every time user swaps mic/camera, the page has to be ready to get rejected for permissions reasons
2. A user could deny access to mic/camera, when the page had been using both.
3. Currently in WebRTC, it's hard to change mic/camera without renegotiating the connection.  During an actual call, showing the gUM prompt means a user could suddenly be absent for seconds or more while they answer the dialog.
4. Confusing user experience; the dialog shows in response to camera or mic selection in-page, and suddenly they're being given yet another, second redundant response.

**Comment by jnoring** [comment] 2016-01-12 16:15
Also, to be clear, this really only becomes a major issue when factoring in the evolution of media capture; I understand why Firefox's original approach could be considered reasonable, but with the addition of navigator.mediaDevices.enumerateDevices and the ability for the page to put together its own UI for camera enumeration and selection, it presents major problems to pages trying to provide consistent, cross-browser UI.

**Comment by mhofman** [comment] 2016-01-12 18:42
I am the original reporter of that issue on the Mozilla bugbase.
While I agree the situation for developers is difficult, as mentioned on the list, I also think the spec shouldn't specify any particular behavior and it can be left to the browser implementor.

After talking to @martinthomson, he believes there might be a way to improve the situation with a spec extension. I'll let him comment on that directly.

**Comment by jnoring** [comment] 2016-01-13 18:58
What's the reasoning behind the spec not specifying any particular behavior?  I think before device enumeration and selection was possible by the page, that design choice makes sense to me.  But it makes less sense given the changes to the spec w/r/t device enumeration and selection, because it sets those two goals on a pretty clear collision course.

I'm open to other suggestions to solve the problem, so the spec extension is an interesting topic of discussion.

**Comment by stefhak** [comment] 2016-01-19 14:11
@martinthomson any comment?

**Comment by stefhak** [comment] 2016-01-20 09:35
Assigning to Martin since it seems from the discussion he may have a proposal. If nothing comes we should close this issue.

**Comment by martinthomson** [comment] 2016-01-20 10:18
See #45.

**Comment by stefhak** [comment] 2016-01-20 12:22
Thanks. Looking at #45 : the gain would be that the app could present images for what each camera is viewing to enable the user to select the right one directly, thus hopefully making a re-select unnecessary. However, it would not help in any way if the user wants to change camera/headset (perhaps to a new one that has just been plugged in). I also guess the UA could already today present such images in the selection UI, it would not be under the app control though.
If we would go this path I guess the images should have an origin that makes it impossible to add them to a canvas and do some processing, and that there should be some rate limitation to prevent the app from sampling, say, twice a second for an extended period. BTW, would it be possible to prevent the app from sending the image off to a server?

**Comment by martinthomson** [comment] 2016-01-21 00:30
Yes, the image would be cross origin, therefore writing to a canvas would mark the canvas as being dirty (disabling readback).  By the same token, the protections would prevent the image from being sent anywhere.

In order to prevent continual sampling of a source (which is an annoyance only, not a real threat), the browser would probably want to cache the images and only update them occasionally.

**Comment by stefhak** [comment] 2016-01-21 08:17
I've consulted the list on whether we should consider adopting #45 : https://lists.w3.org/Archives/Public/public-media-capture/2016Jan/0064.html

**Comment by jnoring** [comment] 2016-01-22 21:52
It doesn't address the basic problem.

The problem is: page creates custom UI for enumeration/selection of devices.  User changes devices.  gUM prompt fires a second time (which offers the user to change their choices--somewhat).  This has several serious consequences, as I mentioned previously:

1. A user could reject the second request (most likely accidentally), which means every time user swaps mic/camera, the page has to be ready to get rejected for permissions reasons.  If they are already chatting with someone, and they are rejected, then that video conference is over.  If they accidentally reject only mic, or only camera, then the page has to account for that and the user experience is bizarre.
2. During an actual call, showing the gUM prompt means a user could be absent for seconds or more while they answer the dialog.
3. Confusing user experience; the dialog shows in response to camera or mic selection in-page, and suddenly they're being given a further permissions dialog.  Some of this can be mitigated by specifying an "exact" device in gUM, but it is still bizarre from a user standpoint.

I don't see how a preview addresses these issues.  It's a cool feature, sure, but it doesn't solve the basic problem between device enumeration/selection and permissions that the spec is rather quiet about.

**Comment by mhofman** [comment] 2016-01-22 23:15
You're correct that this would still allow browsers to prompt for permissions on every confirmed change from the user, and that the user might reject the prompt.

However you already have to deal with the device access potentially failing for other reasons.

Furthermore, I don't fully agree with your assessment that this would result in an interruption to an ongoing call. The application can request the new devices and only switch away from the currently active device once the new device have been accessed successfully. If for some reason you don't get full access to the requested devices (rejected or other failure), you can notify the user and keep the call ongoing with the previously acquired devices.

The exception might be on mobile devices where some platforms are not capable of having 2 webcams active at the same time. However I would expect such platforms to instead expose one camera with a `facingMode` constraint that can be switched between `user` and `environment` using `applyContraints()` on the existing stream. This use case would then not require a new gUM call to switch between front and back camera.

**Comment by jnoring** [comment] 2016-01-22 23:47
@mhofman I don't fully agree with your assessment that I "already have to deal with the device access potentially failing for other reasons."  Beyond the initial gUM request, it isn't a consideration our page has had to make in the past, particularly with the addition of device enumeration.  With Firefox, you're right, we will have to deal with it: some number of users will close the dialog completely.  Some amount will leave tab focus and the dialog will disappear.  Some amount of them will change settings in that dialog, possibly disabling camera/mic entirely.  My opinion is: this discrepancy stems entirely from an incoherent interaction between permissions and device enumeration/selection in this standard.

To your comments about interruptions to ongoing calls, point taken.  We can do that.

**Comment by mhofman** [comment] 2016-01-23 00:23
Your `getUserMedia` calls can fail for reasons other than permissions. E.g. is if the hardware is currently in use in another process (on Windows). You should be handling that flow. If you're not, that's a bug in your application.

**Comment by jnoring** [comment] 2016-01-23 00:33
Agree it's a bug: what I'm telling you is the issue is small enough that frankly it doesn't even measure on the radar.  We do thousands of WebRTC sessions, weekly.  If it were serious, I'm pretty sure I'd have known by now.

**Comment by jan-ivar** [comment] 2016-01-23 04:54
> 1 . A user could reject the second request (most likely accidentally), which means every time user swaps mic/camera, the page has to be ready to get rejected for permissions reasons

@jnoring FYI [the spec allows a UA to stop sharing at any time](http://w3c.github.io/mediacapture-main/getusermedia.html#event-mediastreamtrack-ended). E.g. a Firefox user can click the camera icon in the URL bar at any time and choose "Stop Sharing" ([unfortunately Firefox doesn't fire an event yet](https://bugzil.la/1208373)).

> If they are already chatting with someone, and they are rejected, then that video conference is over.

Video and audio can be added and removed without dropping a call using renegotiation.

> 2 . During an actual call, showing the gUM prompt means a user could be absent for seconds or more while they answer the dialog.

Not if you keep the existing video until you have the new video, although I agree there is a bit of an issue here on mobile devices that can't open more than one camera at a time.

> 3 . Confusing user experience; the dialog shows in response to camera or mic selection in-page, and suddenly they're being given a secondary dialog that seemingly implements the same thing.

This one is a Firefox UX issue and does not belong here.

For this discussion to be useful, lets root it in the spec.

**Comment by jnoring** [comment] 2016-01-23 16:55
> This one is a Firefox UX issue and does not belong here.

I don't agree, because the Firefox UI is permissions (spec issue) interacting strangely with device enumeration and selection (spec issue).  I understand perfectly well that Firefox is conforms to the current spec with regard to permissions, and it conforms with regard to device enumeration and selection, but the resulting experience is bad.  

I'd like to have a spec discussion around this, because here's the reality: device enumeration and selection is a very big deal for users to properly configure their system.  It's the biggest pain point for all of our users.  I understand there are conflicting privacy/security concerns, but as it stands the current spec allows for a UA to craft a UI that's pretty hard for developers to work with, and users to understand.

**Comment by jan-ivar** [comment] 2016-01-23 18:53
@jnoring When used correctly with `deviceId: { exact: id }` - a syntax requirement I fought btw - the fact that the Firefox permission dialog still looks like a device selector when it isn't, is simply a UX bug [which I asked you to file](https://groups.google.com/d/msg/mozilla.dev.media/JIfH7IdFpAg/TmLDd7kVBAAJ). I don't see how you can blame the spec here.

**Comment by jan-ivar** [comment] 2016-01-23 19:10
> However I would expect such platforms to instead expose one camera with a facingMode constraint that can be switched between user and environment using applyContraints() on the existing stream. This use case would then not require a new gUM call to switch between front and back camera.

@mhofman that's an interesting idea, and a good way around the current spec limitations. Unfortunately, none of the mobile browsers do this today. E.g. switching between front and back on Firefox for Android does indeed require relinquishing the front camera *before* the user is asked for permission for the rear camera, and vice versa, which is sub-optimal.

**Comment by mhofman** [comment] 2016-01-26 01:55
> Unfortunately, none of the mobile browsers do this today.

@jan-ivar I just filed bug [1242816](https://bugzil.la/1242816) against Firefox Android for this :smile:

**Comment by stefhak** [comment] 2016-01-27 09:06
Here is a wish expressed to tighten up the spec related to device enumeration, acquiring permissions and UI. However, the discussion (happening here and on the list) does not converge to this being a spec issue (people are rather pointing at implementation issues). Further, the only concrete proposal brought forward ( #45 ) regarding a spec update was not seen as solving this issue. 

Therefore I'm closing this issue. If you think this is wrong: re-open, but make sure to include some extra info (why it should be re-opened, proposal of what can be done, or similar).

**Closed by stefhak** 2016-01-27 09:06 UTC
Labels: List discussion needed
