### ISSUE TITLE
What does it mean that the argument to applyConstraints() is optional

### ISSUE THREAD

**Issue by miguelao** [w3c/mediacapture-main#438] opened 2017-03-16 22:12 UTC
Constrainable Pattern method `applyConstraints()` (defined [here](https://w3c.github.io/mediacapture-main/#media-stream-track-interface-definition) and [here](https://w3c.github.io/mediacapture-main/#interface-definition) (*)) takes an `optional {MediaTrack}Constraints constraints`, but what does it mean to call `applyConstraints()` with no argument? 
Suggest removing the `optional`.

FTR [`Gecko implements it like that`](https://github.com/mozilla/gecko-dev/blob/72823b1e95bed9d3edaff79ebd64c391a33e6d7b/dom/webidl/MediaStreamTrack.webidl#L91) whereas Chrome doesn't have it yet (I'm landing it).

(*) links are broken: I recommend migrating to bikeshed.

**Comment by miguelao** [comment] 2017-03-22 03:43
I think, after ruminating, that an empty parameter means "clear current constraints".  I don't think it's a good idea to encode function behaviour in the semantics of the arguments, and instead we should have a `clearConstraints()` or similar method.

**Comment by alvestrand** [comment] 2017-03-22 07:17
@miguelao don't touch applyConstraints in Chrome without talking to @guidou

Agree that making it optional doesn't seem to make sense, but this is a WebIDL issue; if an argument is a dictionary, and the dictionary has no mandatory members, it MUST be marked optional.

Actually applyConstraints({}) makes some sense ("remove all constraints"), and it's WebIDL dogma that applyConstraints({}) and applyConstraints() should mean exactly the same thing.

Closing as resolved.

**Comment by miguelao** [comment] 2017-03-22 14:35
> @miguelao don't touch applyConstraints in Chrome without talking to @guidou

This issue does not relate to Chrome implementation but to the Spec wording, but thanks for the advice... ? 🤔 .  @guidou let me know if you don't feel in the loop after having reviewed 7 patches of mine related to Constrainable Pattern in the last 7 days :smile:


Although I understand the point that 
>  it's WebIDL dogma  that applyConstraints({}) and applyConstraints() should mean exactly the same thing.

this issue is about what is supposed to happen when `applyConstraints({})` or `applyConstraints()` is called, which is not stated anywhere in the Spec  (also my concern that `encode function behaviour in the semantics of the arguments` is valid).  

At least some editorial comment stating what is supposed to happen when `applyConstraints()` is called with no arguments is needed.

**Comment by alvestrand** [comment] 2017-03-22 14:46
Reopening to address the "but what does it mean to call applyConstraints() with no argument?" question - by WebIDL rules it means exactly the same thing as calling it with an empty dictionary, but what that means should be clear from the spec.

**Comment by guidou** [comment] 2017-03-22 15:42
My interpretation of the current wording of the spec is that applyConstraints should update track and/or source settings to those that best match the new constraints, but without switching the source.
According to the spec, any supported set of settings is equally good at satisfying the empty constraint set, so doing nothing is a valid result for applyConstraints({}). Changing settings to any other supported value (e.g., default values, even random values) is equally spec compliant as long as it doesn't contradict constraints from other tracks.

**Comment by adam-be** [comment] 2017-03-30 11:04
Would the following change clarify the situation?

From the `applyContraints` algorthm:
```
-  2. Let newContraints be the argument to this function
+  2. Let newContraints be the argument to this function, or an empty dictionary if the argument was omitted.
```
Then the empty dictionary would be passed to the `SelectSettings` algorithm.

**Comment by adam-be** [comment] 2017-03-30 11:09
> I think, after ruminating, that an empty parameter means "clear current constraints". I don't think it's a good idea to encode function behaviour in the semantics of the arguments, and instead we should have a clearConstraints() or similar method.

I agree with what you're saying here, but even if we did add a `clearConstraints()` function, `applyContraints()` (with or without an empty dict arg) would still be a duplicate of that behaviour.

**Comment by adam-be** [comment] 2017-04-12 12:57
Ping @miguelao and @guidou

**Comment by guidou** [comment] 2017-04-12 17:18
The proposed wording by @adam-be lgtm

**Comment by miguelao** [comment] 2017-04-12 17:46
The PR lgtm, but the question
> but what does it mean to call applyConstraints() with no argument?

It's still unaddressed: I think at the very least we should include an informative note describing what happens in that case, be that what @guidou [proposes](https://github.com/w3c/mediacapture-main/issues/438#issuecomment-288440738):
>  doing nothing is a valid result for applyConstraints({})

or that it clears up the constraints.

**Comment by guidou** [comment] 2017-04-12 18:10
When I said doing nothing is a valid result, I meant making no changes to the settings of the track (or the underlying implementation).
The track constraints as such should be cleared in the sense that any constraints that existed no longer exist.  Making no changes to the current track settings is compatible with this, since constraints just impose restrictions to the set of valid settings. If constraints are removed, then whatever settings were in place continue to be valid (in fact any other new settings would also be valid as long as they don't violate any other rules).

**Comment by adam-be** [comment] 2017-04-13 07:58
I believe the behaviour is specified by this text (applyConstraints algorithm step 3.3):

```
In a single operation, remove the existing constraints from object, apply
newConstraints, and apply successfulSettings as the current settings.
```

So if a constraint is set by a first call to applyConstraints, it's wiped by the next call if not re-specified. We could clarify this in an info box.

**Closed** 2017-04-20 14:06 UTC
Labels: PR exists

**Comment by jan-ivar** [comment] 2017-05-24 16:08
In case it's not clear from @adam-be 's [comment](https://github.com/w3c/mediacapture-main/issues/438#issuecomment-293820133), `applyConstraints({})` removes all *your* constraints, leaving the device "unconstrained" if you are the only user.¹

<sub>1) Other tabs may be accessing the same device. Constraints are properties of the app, if you will, not the device. </sub>
