### ISSUE TITLE
How should applyConstraints deal with constraints from other tracks sharing the same source?

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-main#465] opened 2017-06-16 13:00 UTC
The description of the SelectSettings algorithm (building block for applyConstraints) explains how to filter candidate settings for a given track given the track's basic and advanced constraint sets.
However, I have a few doubts for the case when the track is connected to a source that is shared with other tracks.
More specifically, my main doubt is that, since the constraints for the other tracks should continue to be satisfied, how should those constraints be taken into account?

Say, T1 has constraint sets B1, A11, A12 and A13 applied, and there is T2 which is sharing the same source as T1. 
T2.applyConstraints is invoked with constraint sets B2, A21, A22,and A23.

Step 3 of SelectSettings says:

> For every possible settings dictionary of copy compute its fitness distance, treating bare values of properties as ideal values. Let candidates be the set of settings dictionaries for which the fitness distance is finite.

What are the "possible settings dictionaries"? Are they all possible dictionaries regardless of their ability to satisfy T1's constraints? Are they only those that satisfy T1's basic constraints? Are they the ones that satisfy T1's basic and advanced? What if some of T1's advanced were ignored during its initialization?

Another question is what role should T1's advanced sets play when resolving T2.applyConstraints.
I assume that T1's basic set must continue to be satisfied, and it is clear what the priority should be for T2's new advanced sets. But, what role should the existing T1 advanced sets play to set the shared source's new configuration?

+minor edit to improve readability and fix typos

**Comment by jan-ivar** [comment] 2017-08-04 14:20
@guidou See https://github.com/w3c/mediacapture-main/issues/394#issuecomment-248542399 for a similar discussion.

To summarize, from https://github.com/w3c/mediacapture-main/issues/394#issuecomment-273583326 we believed the following existing text:

*"The User Agent MAY choose new settings for the constrainable properties of the object at any time. When it does so it MUST attempt to satisfy all current Constraints, in the manner described in the algorithm above."*

..effectively means `applyConstraints` MUST NOT fire `overconstrainederror` events on other tracks. As a result, other tracks implicitly influence the algorithm, by necessitating that we leave out all settings dictionaries that would conflict with existing (mandatory) constraints.

It ends up being a first-come-first-served for mandatory constraints.

Advanced constraints, on the other hand, are optional; never cause errors. How they influence the algorithm is therefore implementation dependent, I think, from these texts : *"The User Agent MAY choose new settings for the constrainable properties of the object at any time. "* and *"Note: When picking a settings dictionary, the UA can use any information available to it."*

This is what Firefox has implemented FWIW. Try opening [this fiddle](https://jsfiddle.net/7udgdbbu/) in two tabs in Firefox. Since Firefox only returns native resolutions and does no rescaling (atm), the changes in one tab may influence the other tab. Originally, we returned an average, but this surprised users, so for width/height we go with max requested.

Does that help?

Btw, we're [dabbling with rescaling now](https://bugzilla.mozilla.org/show_bug.cgi?id=1286945) at least for newer cameras lacking low-resolution modes, and I'm curious how Chrome will work here when it's all finished. I may open a new issue here to discuss some implementation ideas.

**Comment by jan-ivar** [comment] 2017-08-04 14:24
@burnburn In hindsight *"MUST attempt"* seems a bit weak. Was that intentional? Almost a misnomer.

**Comment by burnburn** [comment] 2017-10-10 12:20
I recently gave a presentation on the history of constraints and how they ended up the way they are now.[1]  The original text we had was close to the current text that says 

> The behavior is as follows: all 'min', 'max', and 'exact' constraints in the basic Constraint structure are together treated as the 'required' set, and if it is not possible to satisfy simultaneously all of those individual constraints for the indicated property names, the User Agent MUST reject the returned promise. Otherwise, it must apply the required constraints. Next, it will consider any ConstraintSets given in the 'advanced' list, in the order in which they are specified, and will try to satisfy/apply each complete ConstraintSet (i.e., all constraints in the ConstraintSet together), but will skip a ConstraintSet if and only if it cannot satisfy/apply it in its entirety. Next, the User Agent MUST attempt to apply, individually, any 'ideal' constraints or a constraint given as a bare value for the property. Of these properties, it MUST satisfy the largest number that it can, in any order.

The current selectSettings text was written in an attempt to unify the selection of getUserMedia() with the application of applyConstraints(), but the spirit of the original text may have gotten lost in the process.

When combined with the "you are not allowed to make another track unconstrained" rule that @jan-ivar mentioned and the (original and supposedly-still-present) rule that advanced constraints MUST be satisfied if they can be, making them technically optional but not disregardable, @jan-ivar is correct that in your example T2.applyConstraints() will fail if B2 would make B1 impossible to satisfy.  Beyond that, it is browser choice as to which of the original advanced constraints from T1 and which of the advanced constraints in T2.applyConstraints() to apply, except that, when done, if one of the advanced constraints remains unsatisfied that could be satisfied without invalidating any of the other applied basic or advanced constraints from either track the browser has failed to meet the intent of the algorithm.

It is possible that the existing official description in the specification does not adequately reflect this behavior, but if so we would need specific text suggestions on how to adjust it.  It is definitely unfortunate that the current official text is so different from the original "spirit of" description.

[1] [Slides](https://www.slideshare.net/AmirZ/webrtc-standards-implementation-qa-webrtc-constrains) and [Video](https://www.crowdcast.io/e/webrtcstandards19)

**Comment by jan-ivar** [comment] 2020-01-23 00:50
> It is possible that the existing official description in the specification does not adequately reflect this behavior

I believe the [existing prose](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-applyconstraints-algorithm) adequately represents the original intent here, including the advanced constraints filter: *"The User Agent MAY choose new settings for the constrainable properties of the object at any time. When it does so it ***MUST attempt*** to satisfy ***all*** current Constraints, in the manner described in the ***algorithm above***."*

The _"algorithm above"_ is effectively the [SelectSettings](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-selectsettings) algorithm, which contains:
1. filtering by mandatory constraints (_"the set ... for which the fitness distance is finite"_)
2. pruning by advanced constraints (_"If the fitness distance is finite for one or more"_), and
3. prefer ideal (_"The UA SHOULD use the one with the smallest fitness distance"_)

...in that order.

_"MUST attempt"_ is key here, because while step 1 defines the envelope of settings dictionaries available to the user agent, step 2 by design cannot constrain to zero, but instead produces different results in the face of conflict depending on the order in which multiple concurrent constraint sets are addressed.

Both the original prose and the new prose preserve these steps, but neither say more about in exactly what order concurrent constraints are to be applied, leaving to user agents to attempt any order that produces a pleasing result.

I think leaving this to user agents is fine, and consistent with ideal constraints which similarly have an algorithm with the UA as tie breaker ("SHOULD").

Closing this as no change needed.

**Closed by jan-ivar** 2020-01-23 00:50 UTC
Labels: question
