### ISSUE TITLE
Most browsers lie about how many devices they ask users to share

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#648] opened 2019-12-03 16:36 UTC
As [this slide](https://docs.google.com/presentation/d/1QEdMf6Ixg1NNvHoZUvO29njrSKn9pdF1WqcrFWI4uX8/edit?ts=5dbaf0b6#slide=id.g7915657dd4_6_14) shows, most browsers tell the user they are sharing one camera and one microphone, when in reality they are being asked to share *all* their cameras and microphones:

> Allow "x.com" to use your camera and microphone? _(singular)_

> x.com wants to: use your camera; use your microphone _(singular)_

Instead, it would be accurate to say

> Allow "x.com" to use your cameras and microphones? _(plural)_

> x.com wants to: use your cameras; use your microphones _(plural)_

AFAIK the only browser without this problem is Firefox, which lets users choose one camera + one  mic to share by default (unless the user opts in to all with `☑ Remember this decision`).

As an implementer, I understand browsers aren't doing this maliciously. There are benign reasons for this: words are expensive in prompts, and few users have more than one camera and microphone. But even those users *may* plug in additional devices later, and the spec's current in-content device selection model assumes (as in: only works well when) browsers grant all choices up-front.

That said, now that we're aware this is a problem, I think the spec at minimum needs to more strongly advocate for proper disclosure and understanding in these user interactions.

cc @snyderp

**Comment by alvestrand** [comment] 2019-12-03 18:26
I'll leave @guidou to comment on the lack of progress on changing the singular -> plural for Chrome. I think we've been working on it for 2 years :-(

**Comment by guest271314** [comment] 2019-12-07 19:14
While the topic is at hand the specification could also be improved relevant to selecting `"audiooutput"` directly at `getUserMedia()` execution, instead of listing only "Microphone", where the capability and use cases exist for selecting only output from sound card, not exclusively "Microphone" https://github.com/w3c/mediacapture-main/issues/629#issuecomment-545953051.

**Comment by guest271314** [comment] 2019-12-07 21:00
Consider the code 

```
    (async() => {
      navigator.mediaDevices.ondevicechange = e => console.log(e);
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: {
          deviceId: {
            exact: await navigator.mediaDevices.enumerateDevices()
                   .then(devices =>
                     devices.find(({
                       kind, label, groupId
                     }) => label === "Monitor of Built-in Audio Analog Stereo" // Firefox
                             || kind === "audiooutput" && groupId !== "default" // Chromium
                     ))
                     .deviceId
            }
          }
        });
      const [audioTrack] = stream.getAudioTracks();
      audioTrack.onmute = audioTrack.onended = e => console.log(e);
      const text = [...Array(10).keys()].join(" ");
      const handleVoicesChanged = async e => {
        const voice = speechSynthesis.getVoices().find(({
          name
        }) => name.includes("English"));
        const utterance = new SpeechSynthesisUtterance(text);
        utterance.voice = voice;
        utterance.pitch = 0.33;
        utterance.rate = 0.1;
        const recorder = new MediaRecorder(stream);
        recorder.start();
        speechSynthesis.speak(utterance);
        recorder.ondataavailable = async({
          data
        }) => {
          (new Audio(URL.createObjectURL(data))).play();
        }
        utterance.onend = e => 
          (recorder.state === "recording" && recorder.stop()
          , stream.getAudioTracks()[0].stop());
      }
      speechSynthesis.onvoiceschanged = handleVoicesChanged;
      let voices = speechSynthesis.getVoices();
      if (voices.length) {
        handleVoicesChanged();
      };

    })().catch(console.error);
```

which is intended to select only `"audiooutput"`, not `"Microphone"`. 

Firefox 70 outputs the expected result, that is, capturing and recording only audio output, _not_ input from microphone: Meaning _only_ audio output is captured, _not_ microphone input _and_ audio output.

Chromium 80 does not output the expected result. Even where `"audiooutput"` is selected microphone is captured and recorded, not `"audiooutput"`. That is a Chromium bug that is marked `WontFix` (https://bugs.chromium.org/p/chromium/issues/detail?id=1013881) apparently due to lack of clarity in this specification relevant to the capability to select audio output - not only microphone.

Contrary to the suggestion at https://github.com/w3c/mediacapture-main/issues/629#issuecomment-545844012 `getDisplayMedia()` after testing various approaches, does not provide any means to capture audio output from the system.

Kindly make it clear in this specification that 1) capture of audio output is under the umbrella of this specification and provide an example of the canonical code pattern to achieve that use case per this specification; 2) the user can select `"Monitor of <audio_device>"` at UI prompt and directly in code by use of `applyConstraints()` and directly at `getUserMedia(<constraints>)`; or 3) this specification is _not_ intended to be construed to capture only audio output.

**Closed** 2020-01-09 15:46 UTC
Labels: January 2020 Interim, PR exists

**Comment by youennf** [comment] 2020-01-09 16:56
> AFAIK the only browser without this problem is Firefox

Just want to state that this is a mischaracterisation of Safari behavior.
At the time of the prompt, access is allowed for one camera and/or one microphone.
That is what the user is asked. As a result, one video track and/or one audio track are created.

Safari has then a heuristic that may or may not reuse the decision of the user to any future request may have. There is no guarantee for the page that there will be a prompt (or no prompt), even though the same page might request the exact same device as the previous request.
In that sense, the use of singular seems more appropriate to characterise the question asked to the user.

**Comment by jan-ivar** [comment] 2020-01-09 20:49
@youennf  Thanks for clarifying. I didn't mean to mischaracterize Safari's behavior. I based this on observation, not insight into internal heuristics. But when I run [this code](https://jsfiddle.net/jib1/kvcLyj03/) in Safari on MacOS:
```js
const gUM = constraints => navigator.mediaDevices.getUserMedia(constraints);

video1.srcObject = await gUM({video: true});
const [track1] = video1.srcObject.getVideoTracks();

const devices = await navigator.mediaDevices.enumerateDevices();
const [cam1, cam2] = devices.filter(({kind}) => kind == "videoinput");
const cam = (cam1.deviceId == track1.getSettings().deviceId)? cam2 : cam1;
video2.srcObject = await gUM({video: {deviceId: {exact: cam.deviceId}}});
```
...I get access to two cameras after a single prompt asking for one camera. From an end-user's point of view, who is not privy to these heuristics, this seemed surprising to me given the wording.

**Comment by youennf** [comment] 2020-01-10 15:05
If the presence or not of the 's' is important to convey to the user, it probably means the message is not right since most users will not understand the difference. If the message is not right, maybe we should improve the model.

"Allow access to camera(s)" is an ambiguous sentence by design, especially since it is so short.
For instance, does it mean all cameras connected now or also the future cameras? For this page or for all pages of this origin?

Fortunately, users have some context since they probably already answered to OS permission requests. They will probably interpret the message according to this knowledge.
Safari prompt is consistent with MacOS and iOS system prompts for camera and microphone.

> I get access to two cameras after a single prompt asking for one camera.

The typical use case is an iPhone user with a back camera and a front camera.
When a user grants camera access, I believe it is intuitive to the user that the web app gets access to both front and back camera.

If the heuristic is found counterintuitive, I agree it is appropriate to try improving it, or changing the model...
