### ISSUE TITLE
Clarify when to fire devicechange event for changes of device capabilities

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#730] opened 2020-10-01 14:33 UTC
Devices may not be added or removed but their capabilities or labels may changed.
In that case, it might be good to fire a devicechange event provided labels are exposed.

**Comment by guest271314** [comment] 2020-10-01 23:52
Devices can be added and removed. Plug and play USB devices, Bluetooth devices, virtual devices. Firing `devicechange` has nothing to do with listing the incorrect device if incorrect device is still listed.

**Comment by guest271314** [comment] 2020-10-02 00:04
The issue is Chromium refuses to list or capture audio devices that include monitor text in device description at Linux. To workaround that arbitrary restriction it is possible to dynamically change and set the devices being captured to a monitor device https://bugs.chromium.org/p/chromium/issues/detail?id=931749, thus, when the device changes not only must a `devicechange` event be fired but also the correct device being captured needs to be listed at `enumerateDevices()`, in spite of Chromium in-house decisions imposing restrictions of device capture. Firing `devicechange` alone in this case will not solve the bug that https://github.com/w3c/mediacapture-main/issues/693 was filed for if the exact same devices are listed.

**Comment by jan-ivar** [comment] 2020-10-20 00:24
I think we have to be careful not to disturb what I think is the primary use case of `devicechange`:
* Detecting user insertion (or bluetooth activation) of a new device (_meaning: user intends to use this device_)

Recall: the event is insufficient, apps must diff `enumerateDevices` results (after gUM grant!) before and after the event.

Hopefully apps are diffing only on `deviceId`s. But if they're not (diffing on the entire entry or `label`), then changing a `label` may trigger a false positive insertion (apps thinking the user wants to use new device when they don't).

**Comment by alvestrand** [comment] 2020-11-19 15:54
Not clear how properties such as label would change, or whether browsers would be able to detect it (apart from polling).

**Comment by jan-ivar** [comment] 2020-11-19 15:55
This seems like a user agent configuration issue, and it's not clear there's value in standardizing what they should do here. Closing as no action needed.

**Closed** 2020-11-19 15:55 UTC
